plugins {
  id 'java-library'
  id 'idea'
  id 'antlr'
  id 'com.adarshr.test-logger' version '4.0.0'
}


layout.buildDirectory = '.build'


description = 'ANTLR4 Runtime Extensions'
group = 'de.sayayi.lib'
version = libs.versions.antlr4.runtime.ext.get()


configurations {
  api {
    // get rid of antlr4 configuration dependency, which will include antlr4.jar
    extendsFrom = extendsFrom.findAll { it != configurations.antlr }
  }
}


java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }

  withSourcesJar()
  withJavadocJar()
}


test {
  useJUnitPlatform()

  javaLauncher = javaToolchains.launcherFor {
    languageVersion = JavaLanguageVersion.of(21)
  }
}


testlogger {
  theme = 'mocha'
  slowThreshold = 3500
}


repositories {
  mavenCentral()
}


dependencies {
  // java
  implementation libs.antlr4.runtime

  compileOnlyApi libs.jetbrains.annotations

  // test
  testAnnotationProcessor libs.lombok

  testCompileOnly libs.lombok
  testCompileOnly libs.jetbrains.annotations

  testImplementation libs.junit.jupiter.api
  testRuntimeOnly libs.junit.jupiter.engine
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

  antlr libs.antlr4
}


compileTestJava.dependsOn generateTestGrammarSource


def resolvedAntlr4RuntimeVersion = configurations
    .compileClasspath
    .resolvedConfiguration
    .resolvedArtifacts
    .find { it.name == 'antlr4-runtime' }
    .moduleVersion.id.version

def resolvedJetbrainsAnnotationsVersion = configurations
    .compileClasspath
    .resolvedConfiguration
    .resolvedArtifacts
    .find { it.name == 'annotations' }
    .moduleVersion.id.version


javadoc {
  title = "ANTLR4 Runtime Extensions ${version}"

  (options as StandardJavadocDocletOptions).with {
    linksOffline "https://javadoc.io/doc/org.jetbrains/annotations/${resolvedJetbrainsAnnotationsVersion}/",
                 'gradle/javadocs/jetbrains-annotations'
    linksOffline "https://javadoc.io/doc/org.antlr/antlr4-runtime/${resolvedAntlr4RuntimeVersion}/",
                 'gradle/javadocs/antlr4-runtime'

    encoding 'UTF-8'

    group("ANTLR4 Runtime API", [
        'de.sayayi.lib.antlr4',
        'de.sayayi.lib.antlr4.syntax',
        'de.sayayi.lib.antlr4.walker'
    ])

    noQualifiers 'java.util', 'java.lang'

    addStringOption('Xdoclint:-missing', '-quiet')
    //addStringOption('no-module-directories', '')
  }

  failOnError = false
}


tasks.withType(Jar).configureEach {
  reproducibleFileOrder = true

  manifest {
    attributes(
        'Implementation-Vendor': 'Jeroen Gremmen',
        'Implementation-Vendor-Id': 'de.sayayi',
        'Implementation-Title': project.name,
        'Implementation-Version': project.version,
        'Created-By': System.getProperty('java.version'),
        'Built-Date': new Date().format('yyyy-MM-dd HH:mm:ss')
    )
  }

  metaInf {
    from files('LICENSE')
  }
}


jar.dependsOn test


apply from: 'gradle/publish.gradle'


clean {
  delete layout.projectDirectory.dir('build')
}


wrapper {
  distributionType = Wrapper.DistributionType.BIN
}


idea {
  module {
    generatedSourceDirs += generateTestGrammarSource.outputDirectory
  }
}
